---
- hosts: webservers
  become: True
  tasks:
    - name: pull an image
      docker_image:
        name: 10.220.110.10:8083/halosys:docker_tag
        
    - name: Create a container  
      docker_container:
        name: ansibledeployment
        image: 10.220.110.10:8083/halosys:docker_tag
        ports:
          - "1181:8080"      
...
